Country.create([{ name: 'afghanistan', esp_name: 'afganistán', abbreviation: 'af', code: '004'	},
{ name: 'aland islands', esp_name: 'islas de åland', abbreviation: 'ax', code: '248'	},
{ name: 'albania', esp_name: 'albania', abbreviation: 'al', code: '008'	},
{ name: 'algeria', esp_name: 'argelia', abbreviation: 'ag', code: '012'	},
{ name: 'american samoa', esp_name: 'samoa americana', abbreviation: 'aq', code: '016'	},
{ name: 'andorra', esp_name: 'andorra', abbreviation: 'an', code: '020'	},
{ name: 'angola', esp_name: 'angola', abbreviation: 'ao', code: '024'	},
{ name: 'anguilla', esp_name: 'anguila', abbreviation: 'av', code: '660'	},
{ name: 'antarctica', esp_name: 'antartica', abbreviation: 'ay', code: '010'	},
{ name: 'antigua and barbuda', esp_name: 'antigua & barbuda', abbreviation: 'ac', code: '028'	},
{ name: 'argentina', esp_name: 'argentina', abbreviation: 'ar', code: '032'	},
{ name: 'armenia', esp_name: 'armenia', abbreviation: 'am', code: '051'	},
{ name: 'aruba', esp_name: 'aruba', abbreviation: 'aa', code: '533'	},
{ name: 'australia', esp_name: 'australia', abbreviation: 'as', code: '036'	},
{ name: 'austria', esp_name: 'austria', abbreviation: 'au', code: '040'	},
{ name: 'azerbaijan', esp_name: 'azerbaiyán', abbreviation: 'aj', code: '031'	},
{ name: 'bahamas, the', esp_name: 'las bahamas', abbreviation: 'bf', code: '044'	},
{ name: 'bahrain', esp_name: 'barein', abbreviation: 'ba', code: '048'	},
{ name: 'bangladesh', esp_name: 'bangladesh', abbreviation: 'bg', code: '050'	},
{ name: 'barbados', esp_name: 'barbados', abbreviation: 'bb', code: '052'	},
{ name: 'belarus', esp_name: 'bielorrusia', abbreviation: 'bo', code: '112'	},
{ name: 'belgium', esp_name: 'bélgica', abbreviation: 'be', code: '056'	},
{ name: 'belize', esp_name: 'belice', abbreviation: 'bh', code: '084'	},
{ name: 'benin', esp_name: 'benin', abbreviation: 'bn', code: '204'	},
{ name: 'bermuda', esp_name: 'bermuda', abbreviation: 'bd', code: '060'	},
{ name: 'bhutan', esp_name: 'bután', abbreviation: 'bt', code: '064'	},
{ name: 'bolivia', esp_name: 'bolivia', abbreviation: 'bl', code: '068'	},
{ name: 'bosnia and herzegovina', esp_name: 'bosnia y herzegovina', abbreviation: 'bk', code: '070'	},
{ name: 'botswana', esp_name: 'botsuana', abbreviation: 'bc', code: '072'	},
{ name: 'bouvet island', esp_name: 'isla bouvet', abbreviation: 'bv', code: '074'	},
{ name: 'br indian ocean terr', esp_name: 'territorio británico oce. indico', abbreviation: 'io', code: '086'	},
{ name: 'brazil', esp_name: 'brasil', abbreviation: 'br', code: '076'	},
{ name: 'british virgin is.', esp_name: 'islas vírgenes', abbreviation: 'vi', code: '092'	},
{ name: 'brunei', esp_name: 'brunei', abbreviation: 'bx', code: '096'	},
{ name: 'bulgaria', esp_name: 'bulgaria', abbreviation: 'bu', code: '100'	},
{ name: 'burkina', esp_name: 'burkina', abbreviation: 'uv', code: '854'	},
{ name: 'burma', esp_name: 'burma', abbreviation: 'bm', code: '104'	},
{ name: 'burundi', esp_name: 'burundi', abbreviation: 'by', code: '108'	},
{ name: 'cambodia', esp_name: 'camboya', abbreviation: 'cb', code: '116'	},
{ name: 'cameroon', esp_name: 'camerún', abbreviation: 'cm', code: '120'	},
{ name: 'canada', esp_name: 'canadá', abbreviation: 'ca', code: '124'	},
{ name: 'cape verde', esp_name: 'cabo verde', abbreviation: 'cv', code: '132'	},
{ name: 'cayman islands', esp_name: 'islas caimán', abbreviation: 'cj', code: '136'	},
{ name: 'central african rep.', esp_name: 'república centroafricana', abbreviation: 'ct', code: '140'	},
{ name: 'chad', esp_name: 'chad', abbreviation: 'cd', code: '148'	},
{ name: 'chile', esp_name: 'chile', abbreviation: 'ci', code: '152'	},
{ name: 'china', esp_name: 'china', abbreviation: 'ch', code: '156'	},
{ name: 'christmas island', esp_name: 'isla de navidad', abbreviation: 'kt', code: '162'	},
{ name: 'cocos (keeling) islands', esp_name: 'islas cocos', abbreviation: 'ck', code: '166'	},
{ name: 'colombia', esp_name: 'colombia', abbreviation: 'co', code: '170'	},
{ name: 'comoros', esp_name: 'comoros', abbreviation: 'cn', code: '174'	},
{ name: 'congo', esp_name: 'congo', abbreviation: 'cf', code: '178'	},
{ name: 'congo, democratic republic of the', esp_name: 'república democrática del congo', abbreviation: 'cg', code: '180'	},
{ name: 'cook islands', esp_name: 'islas cook', abbreviation: 'cw', code: '184'	},
{ name: 'costa rica', esp_name: 'costa rica', abbreviation: 'cs', code: '188'	},
{ name: "cote d'ivoire", esp_name: 'costa de marfil', abbreviation: 'iv', code: '384'	},
{ name: 'croatia', esp_name: 'croacia', abbreviation: 'hr', code: '191'	},
{ name: 'cuba', esp_name: 'cuba', abbreviation: 'cu', code: '192'	},
{ name: 'cyprus', esp_name: 'chipre', abbreviation: 'cy', code: '196'	},
{ name: 'czech republic', esp_name: 'república checa', abbreviation: 'ez', code: '203'	},
{ name: 'denmark', esp_name: 'dinamarca', abbreviation: 'da', code: '208'	},
{ name: 'dijibouti', esp_name: 'yibuti', abbreviation: 'dj', code: '262'	},
{ name: 'dominica', esp_name: 'dominica', abbreviation: 'do', code: '212'	},
{ name: 'dominican republic', esp_name: 'república dominicana', abbreviation: 'dr', code: '214'	},
{ name: 'ecuador', esp_name: 'ecuador', abbreviation: 'ec', code: '218'	},
{ name: 'egypt', esp_name: 'egipto', abbreviation: 'eg', code: '818'	},
{ name: 'el salvador', esp_name: 'el salvador', abbreviation: 'es', code: '222'	},
{ name: 'equatorial guinea', esp_name: 'guinea ecuatorial', abbreviation: 'ek', code: '226'	},
{ name: 'eritrea', esp_name: 'eritrea', abbreviation: 'er', code: '232'	},
{ name: 'estonia', esp_name: 'estonia', abbreviation: 'en', code: '233'	},
{ name: 'ethiopia', esp_name: 'etiopía', abbreviation: 'et', code: '231'	},
{ name: 'falkland (is malvinas)', esp_name: 'islas malvinas', abbreviation: 'fk', code: '238'	},
{ name: 'faroe islands', esp_name: 'islas faroe', abbreviation: 'fo', code: '234'	},
{ name: 'fed states micronesia', esp_name: 'estados federados de micronesia', abbreviation: 'fm', code: '583'	},
{ name: 'fiji', esp_name: 'fiji', abbreviation: 'fj', code: '242'	},
{ name: 'finland', esp_name: 'finlandia', abbreviation: 'fi', code: '246'	},
{ name: 'fr so & antarctic lnds', esp_name: 'tierras australes y antárticas francesas', abbreviation: 'fs', code: '260'	},
{ name: 'france', esp_name: 'francia', abbreviation: 'fr', code: '250'	},
{ name: 'french guiana', esp_name: 'guyana francesa', abbreviation: 'fg', code: '254'	},
{ name: 'french polynesia', esp_name: 'polinesia francesa', abbreviation: 'fp', code: '258'	},
{ name: 'gabon', esp_name: 'gabón', abbreviation: 'gb', code: '266'	},
{ name: 'gambia, the', esp_name: 'gambia', abbreviation: 'ga', code: '270'	},
{ name: 'georgia', esp_name: 'georgia', abbreviation: 'gg', code: '268'	},
{ name: 'germany', esp_name: 'alemania', abbreviation: 'gm', code: '276'	},
{ name: 'ghana', esp_name: 'ghana', abbreviation: 'gh', code: '288'	},
{ name: 'gibraltar', esp_name: 'gibraltar', abbreviation: 'gi', code: '292'	},
{ name: 'greece', esp_name: 'grecia', abbreviation: 'gr', code: '300'	},
{ name: 'greenland', esp_name: 'groenlandia', abbreviation: 'gl', code: '304'	},
{ name: 'grenada', esp_name: 'granada', abbreviation: 'gj', code: '308'	},
{ name: 'guadeloupe', esp_name: 'guadalupe', abbreviation: 'gp', code: '312'	},
{ name: 'guam', esp_name: 'guam', abbreviation: 'gq', code: '316'	},
{ name: 'guatemala', esp_name: 'guatemala', abbreviation: 'gt', code: '320'	},
{ name: 'guernsey', esp_name: 'guernsey', abbreviation: 'gk', code: '831'	},
{ name: 'guinea', esp_name: 'guinea', abbreviation: 'gv', code: '324'	},
{ name: 'guinea-bissau', esp_name: 'guinea-bissau', abbreviation: 'pu', code: '624'	},
{ name: 'guyana', esp_name: 'guyana', abbreviation: 'gy', code: '328'	},
{ name: 'haiti', esp_name: 'haití', abbreviation: 'ha', code: '332'	},
{ name: 'heard is&mcdonald isls', esp_name: 'islas heard y mcdonald', abbreviation: 'hm', code: '334'	},
{ name: 'honduras', esp_name: 'honduras', abbreviation: 'ho', code: '340'	},
{ name: 'hong kong', esp_name: 'hong kong', abbreviation: 'hk', code: '344'	},
{ name: 'hungary', esp_name: 'hungría', abbreviation: 'hu', code: '348'	},
{ name: 'iceland', esp_name: 'islandia', abbreviation: 'ic', code: '352'	},
{ name: 'india', esp_name: 'india', abbreviation: 'in', code: '356'	},
{ name: 'indonesia', esp_name: 'indonesia', abbreviation: 'id', code: '360'	},
{ name: 'iran', esp_name: 'irán', abbreviation: 'ir', code: '364'	},
{ name: 'iraq', esp_name: 'irak', abbreviation: 'iz', code: '368'	},
{ name: 'ireland', esp_name: 'irlanda', abbreviation: 'ei', code: '372'	},
{ name: 'israel', esp_name: 'israel', abbreviation: 'is', code: '376'	},
{ name: 'italy', esp_name: 'italia', abbreviation: 'it', code: '380'	},
{ name: 'jamaica', esp_name: 'jamaica', abbreviation: 'jm', code: '388'	},
{ name: 'japan', esp_name: 'japón', abbreviation: 'ja', code: '392'	},
{ name: 'jersey', esp_name: 'jersey', abbreviation: 'je', code: '832'	},
{ name: 'jordan', esp_name: 'jordania', abbreviation: 'jo', code: '400'	},
{ name: 'kazakhstan', esp_name: 'kazajistán', abbreviation: 'kz', code: '398'	},
{ name: 'kenya', esp_name: 'kenia', abbreviation: 'ke', code: '404'	},
{ name: 'kiribati', esp_name: 'kiribati', abbreviation: 'kr', code: '296'	},
{ name: 'korea, republic of', esp_name: 'corea del sur', abbreviation: 'ks', code: '410'	},
{ name: 'korea,dem peoples rep', esp_name: 'corea del norte', abbreviation: 'kn', code: '408'	},
{ name: 'kuwait', esp_name: 'kuwait', abbreviation: 'ku', code: '414'	},
{ name: 'kyrgyzstan', esp_name: 'kirguistán', abbreviation: 'kg', code: '417'	},
{ name: 'laos', esp_name: 'laos', abbreviation: 'la', code: '418'	},
{ name: 'latvia', esp_name: 'letonia', abbreviation: 'lg', code: '428'	},
{ name: 'lebanon', esp_name: 'líbano', abbreviation: 'le', code: '422'	},
{ name: 'lesotho', esp_name: 'lesoto', abbreviation: 'lt', code: '426'	},
{ name: 'liberia', esp_name: 'liberia', abbreviation: 'li', code: '430'	},
{ name: 'libya', esp_name: 'libia', abbreviation: 'ly', code: '434'	},
{ name: 'liechtenstein', esp_name: 'liechtenstein', abbreviation: 'ls', code: '438'	},
{ name: 'lithuania', esp_name: 'lituania', abbreviation: 'lh', code: '440'	},
{ name: 'luxembourg', esp_name: 'luxemburgo', abbreviation: 'lu', code: '442'	},
{ name: 'macau', esp_name: 'macao', abbreviation: 'mc', code: '446'	},
{ name: 'macedonia', esp_name: 'macedonia', abbreviation: 'mk', code: '807'	},
{ name: 'madagascar', esp_name: 'madagascar', abbreviation: 'ma', code: '450'	},
{ name: 'malawi', esp_name: 'malawi', abbreviation: 'mi', code: '454'	},
{ name: 'malaysia', esp_name: 'malasia', abbreviation: 'my', code: '458'	},
{ name: 'maldives', esp_name: 'maldivas', abbreviation: 'mv', code: '462'	},
{ name: 'mali', esp_name: 'mali', abbreviation: 'ml', code: '466'	},
{ name: 'malta', esp_name: 'malta', abbreviation: 'mt', code: '470'	},
{ name: 'man, isle of', esp_name: 'isla de man', abbreviation: 'im', code: '833'	},
{ name: 'marshall islands', esp_name: 'islas marshall', abbreviation: 'rm', code: '584'	},
{ name: 'martinique', esp_name: 'martinica', abbreviation: 'mb', code: '474'	},
{ name: 'mauritania', esp_name: 'mauritania', abbreviation: 'mr', code: '478'	},
{ name: 'mauritius', esp_name: 'mauricio', abbreviation: 'mp', code: '480'	},
{ name: 'mayotte', esp_name: 'mayotte', abbreviation: 'mf', code: '175'	},
{ name: 'mexico', esp_name: 'méxico', abbreviation: 'mx', code: '484'	},
{ name: 'moldova', esp_name: 'moldavia', abbreviation: 'md', code: '498'	},
{ name: 'monaco', esp_name: 'mónaco', abbreviation: 'mn', code: '492'	},
{ name: 'mongolia', esp_name: 'mongolia', abbreviation: 'mg', code: '496'	},
{ name: 'montenegro', esp_name: 'montenegro', abbreviation: 'mj', code: '499'	},
{ name: 'montserrat', esp_name: 'montserrat', abbreviation: 'ms', code: '500'	},
{ name: 'morocco', esp_name: 'marruecos', abbreviation: 'mo', code: '504'	},
{ name: 'mozambique', esp_name: 'mozambique', abbreviation: 'mz', code: '508'	},
{ name: 'namibia', esp_name: 'namibia', abbreviation: 'wa', code: '516'	},
{ name: 'nauru', esp_name: 'nauru', abbreviation: 'nr', code: '520'	},
{ name: 'nepal', esp_name: 'nepal', abbreviation: 'np', code: '524'	},
{ name: 'netherlands', esp_name: 'holanda', abbreviation: 'nl', code: '528'	},
{ name: 'netherlands antilles', esp_name: 'antillas holandesas', abbreviation: 'nt', code: '530'	},
{ name: 'new caledonia', esp_name: 'nueva caledonia', abbreviation: 'nc', code: '540'	},
{ name: 'new zealand', esp_name: 'nueva zelandia', abbreviation: 'nz', code: '554'	},
{ name: 'nicaragua', esp_name: 'nicaragua', abbreviation: 'nu', code: '558'	},
{ name: 'niger', esp_name: 'níger', abbreviation: 'ng', code: '562'	},
{ name: 'nigeria', esp_name: 'nigeria', abbreviation: 'ni', code: '566'	},
{ name: 'niue', esp_name: 'niue', abbreviation: 'ne', code: '570'	},
{ name: 'norfolk island', esp_name: 'isla norfolk', abbreviation: 'nf', code: '574'	},
{ name: 'northern mariana is', esp_name: 'islas marianas del norte', abbreviation: 'cq', code: '580'	},
{ name: 'norway', esp_name: 'noruega', abbreviation: 'no', code: '578'	},
{ name: 'oman', esp_name: 'omán', abbreviation: 'mu', code: '512'	},
{ name: 'pakistan', esp_name: 'pakistán', abbreviation: 'pk', code: '586'	},
{ name: 'palestinian territory, occupied', esp_name: 'territorio palestino ocupado', abbreviation: 'ps', code: '275'	},
{ name: 'panama', esp_name: 'panamá', abbreviation: 'pa', code: '591'	},
{ name: 'papua new guinea', esp_name: 'papua nueva guinea', abbreviation: 'pp', code: '598'	},
{ name: 'paraguay', esp_name: 'paraguay', abbreviation: 'py', code: '600'	},
{ name: 'palau republic of', esp_name: 'palaos', abbreviation: 'ps', code: '275'	},
{ name: 'peru', esp_name: 'perú', abbreviation: 'pe', code: '604'	},
{ name: 'philippines', esp_name: 'filipinas', abbreviation: 'rp', code: '608'	},
{ name: 'pitcairn islands', esp_name: 'islas pitcáirn', abbreviation: 'pc', code: '612'	},
{ name: 'poland', esp_name: 'polonia', abbreviation: 'pl', code: '616'	},
{ name: 'portugal', esp_name: 'portugal', abbreviation: 'po', code: '620'	},
{ name: 'puerto rico', esp_name: 'puerto rico', abbreviation: 'rq', code: '630'	},
{ name: 'qatar', esp_name: 'catar', abbreviation: 'qa', code: '634'	},
{ name: 'reunion', esp_name: 'reunión', abbreviation: 're', code: '638'	},
{ name: 'romania', esp_name: 'rumania', abbreviation: 'ro', code: '642'	},
{ name: 'russia', esp_name: 'rusia', abbreviation: 'rs', code: '643'	},
{ name: 'rwanda', esp_name: 'ruanda', abbreviation: 'rw', code: '646'	},
{ name: 's.georgia/s.sandwic is', esp_name: 'islas georgia del sur y sandwich del sur', abbreviation: 'sx', code: '239'	},
{ name: 'san marino', esp_name: 'san marino', abbreviation: 'sm', code: '674'	},
{ name: 'sao tome and principe', esp_name: 'santo tomé y principe', abbreviation: 'tp', code: '678'	},
{ name: 'saudi arabia', esp_name: 'arabia saudita', abbreviation: 'sa', code: '682'	},
{ name: 'senegal', esp_name: 'senegal', abbreviation: 'sg', code: '686'	},
{ name: 'serbia', esp_name: 'serbia', abbreviation: 'ri', code: '688'	},
{ name: 'seychelles', esp_name: 'seychelles', abbreviation: 'se', code: '690'	},
{ name: 'sierra leone', esp_name: 'sierra leona', abbreviation: 'sl', code: '694'	},
{ name: 'singapore', esp_name: 'singapur', abbreviation: 'sn', code: '702'	},
{ name: 'slovakia', esp_name: 'eslovaquia', abbreviation: 'lo', code: '703'	},
{ name: 'slovenia', esp_name: 'eslovenia', abbreviation: 'si', code: '705'	},
{ name: 'solomon islands', esp_name: 'islas salomón', abbreviation: 'bp', code: '090'	},
{ name: 'somalia', esp_name: 'somalia', abbreviation: 'so', code: '706'	},
{ name: 'south africa', esp_name: 'sudáfica', abbreviation: 'sf', code: '710'	},
{ name: 'south sudan', esp_name: 'sudán de sur', abbreviation: 'od', code: '728'	},
{ name: 'spain', esp_name: 'españa', abbreviation: 'sp', code: '724'	},
{ name: 'sri lanka', esp_name: 'sri lanka', abbreviation: 'ce', code: '144'	},
{ name: 'st lucia', esp_name: 'santa lucía', abbreviation: 'st', code: '662'	},
{ name: 'st. helena', esp_name: 'isla santa elena', abbreviation: 'sh', code: '654'	},
{ name: 'st. kitts and nevis', esp_name: 'san crisóbal y nieves', abbreviation: 'sc', code: '659'	},
{ name: 'st. pierre and miquelon', esp_name: 'san pedro y miguelón', abbreviation: 'sb', code: '666'	},
{ name: 'st. vincent/grenadines', esp_name: 'san vicente y las granadinas', abbreviation: 'vc', code: '670'	},
{ name: 'st.barthelemy', esp_name: 'san bartolomé', abbreviation: 'bl', code: '652'	},
{ name: 'st.martin', esp_name: 'isla de san martín', abbreviation: 'mf', code: '663'	},
{ name: 'sudan', esp_name: 'sudán', abbreviation: 'su', code: '736'	},
{ name: 'suriname', esp_name: 'surinam', abbreviation: 'ns', code: '740'	},
{ name: 'swaziland', esp_name: 'suazilandia', abbreviation: 'wz', code: '748'	},
{ name: 'sweden', esp_name: 'suecia', abbreviation: 'sw', code: '752'	},
{ name: 'switzerland', esp_name: 'suiza', abbreviation: 'sz', code: '756'	},
{ name: 'syria', esp_name: 'siria', abbreviation: 'sy', code: '760'	},
{ name: 'taiwan', esp_name: 'taiwán', abbreviation: 'tw', code: '158'	},
{ name: 'tajikistan', esp_name: 'tajikistán', abbreviation: 'ti', code: '762'	},
{ name: 'tanzania, united rep of', esp_name: 'tanzania', abbreviation: 'tz', code: '834'	},
{ name: 'thailand', esp_name: 'tailandia', abbreviation: 'th', code: '764'	},
{ name: 'timor-leste', esp_name: 'timor oriental', abbreviation: 'tt', code: '626'	},
{ name: 'togo', esp_name: 'togo', abbreviation: 'to', code: '768'	},
{ name: 'tokelau', esp_name: 'tokelau', abbreviation: 'tl', code: '772'	},
{ name: 'tonga', esp_name: 'tonga', abbreviation: 'tn', code: '776'	},
{ name: 'trinidad and tobago', esp_name: 'trinidad y tobago', abbreviation: 'td', code: '780'	},
{ name: 'tunisia', esp_name: 'túnez', abbreviation: 'ts', code: '788'	},
{ name: 'turkey', esp_name: 'turquía', abbreviation: 'tu', code: '792'	},
{ name: 'turkmenistan', esp_name: 'turkmenistán', abbreviation: 'tx', code: '795'	},
{ name: 'turks and caicos isl', esp_name: 'islas turcas y caicos', abbreviation: 'tk', code: '796'	},
{ name: 'tuvalu', esp_name: 'tuvalu', abbreviation: 'tv', code: '798'	},
{ name: 'u.s. minor outlying isl', esp_name: 'islas ultramarinas e.e.u.u', abbreviation: 'um', code: '581'	},
{ name: 'uganda', esp_name: 'uganda', abbreviation: 'ug', code: '800'	},
{ name: 'ukraine', esp_name: 'ucraina', abbreviation: 'up', code: '804'	},
{ name: 'united arab emirates', esp_name: 'emirato árabes unidos', abbreviation: 'ae', code: '784'	},
{ name: 'united kingdom', esp_name: 'reino unido', abbreviation: 'uk', code: '826'	},
{ name: 'united states', esp_name: 'estados unidos', abbreviation: 'us', code: '840'	},
{ name: 'uruguay', esp_name: 'uruguay', abbreviation: 'uy', code: '858'	},
{ name: 'uzbekistan', esp_name: 'uzbekistán', abbreviation: 'uz', code: '860'	},
{ name: 'vanuatu', esp_name: 'vanuatu', abbreviation: 'nh', code: '548'	},
{ name: 'vatican city', esp_name: 'ciudad del vaticano', abbreviation: 'vt', code: '336'	},
{ name: 'venezuela', esp_name: 'venezuela', abbreviation: 've', code: '862'	},
{ name: 'vietnam', esp_name: 'vietnam', abbreviation: 'vm', code: '704'	},
{ name: 'virgin islands', esp_name: 'islas vírgenes', abbreviation: 'vq', code: '850'	},
{ name: 'wallis and futuna', esp_name: 'wallis y futuna', abbreviation: 'wf', code: '876'	},
{ name: 'western sahara', esp_name: 'sahara occidental', abbreviation: 'wi', code: '732'	},
{ name: 'western samoa', esp_name: 'samoa occidental', abbreviation: 'ws', code: '882'	},
{ name: 'yemen', esp_name: 'yemén', abbreviation: 'ym', code: '887'	},
{ name: 'zambia', esp_name: 'zambia', abbreviation: 'za', code: '894'	},
{ name: 'zimbabwe', esp_name: 'zimbabue', abbreviation: 'zi', code: '716'	}])
