#encoding: UTF-8
District.create([
  {province_id: 1, name: 'bocas del toro'},
  {province_id: 1, name: 'changuinola'},
  {province_id: 1, name: 'chiriquí grande'},
  {province_id: 2, name: 'aguadulce'},
  {province_id: 2, name: 'antón'},
  {province_id: 2, name: 'la pintada'},
  {province_id: 2, name: 'natá'},
  {province_id: 2, name: 'olá'},
  {province_id: 2, name: 'penonomé'},
  {province_id: 3, name: 'colón'},
  {province_id: 3, name: 'chagres'},
  {province_id: 3, name: 'donoso'},
  {province_id: 3, name: 'portobelo'},
  {province_id: 3, name: 'santa isabel'},
  {province_id: 4, name: 'alanje'},
  {province_id: 4, name: 'barú'},
  {province_id: 4, name: 'boquerón'},
  {province_id: 4, name: 'boquete'},
  {province_id: 4, name: 'bugaba'},
  {province_id: 4, name: 'david'},
  {province_id: 4, name: 'dolega'},
  {province_id: 4, name: 'gualaca'},
  {province_id: 4, name: 'remedios'},
  {province_id: 4, name: 'renacimiento'},
  {province_id: 4, name: 'san félix'},
  {province_id: 4, name: 'san lorenzo'},
  {province_id: 4, name: 'tolé'},
  {province_id: 5, name: 'chepigana'},
  {province_id: 5, name: 'pinogana'},
  {province_id: 6, name: 'chitré'},
  {province_id: 6, name: 'las minas'},
  {province_id: 6, name: 'los pozos'},
  {province_id: 6, name: 'ocú'},
  {province_id: 6, name: 'parita'},
  {province_id: 6, name: 'pesé'},
  {province_id: 6, name: 'santa maría'},
  {province_id: 7, name: 'guararé'},
  {province_id: 7, name: 'las tablas'},
  {province_id: 7, name: 'los santos'},
  {province_id: 7, name: 'macaracas'},
  {province_id: 7, name: 'pedasí'},
  {province_id: 7, name: 'pocrí'},
  {province_id: 7, name: 'tonosí'},
  {province_id: 8, name: 'balboa'},
  {province_id: 8, name: 'chepo'},
  {province_id: 8, name: 'chimán'},
  {province_id: 8, name: 'panamá'},
  {province_id: 8, name: 'san miguelito'},
  {province_id: 8, name: 'taboga'},
  {province_id: 13, name: 'la chorrera'},
  {province_id: 13, name: 'arraiján'},
  {province_id: 13, name: 'san carlos'},
  {province_id: 13, name: 'capira'},
  {province_id: 13, name: 'chame'},
  {province_id: 9, name: 'atalaya'},
  {province_id: 9, name: 'calobre'},
  {province_id: 9, name: 'cañazas'},
  {province_id: 9, name: 'la mesa'},
  {province_id: 9, name: 'las palmas'},
  {province_id: 9, name: 'mariato'},
  {province_id: 9, name: 'montijo'},
  {province_id: 9, name: 'río de jesús'},
  {province_id: 9, name: 'san francisco'},
  {province_id: 9, name: 'santa fe'},
  {province_id: 9, name: 'santiago'},
  {province_id: 9, name: 'soná'},
  {province_id: 10, name: 'ailigandi'},
  {province_id: 10, name: 'narganá'},
  {province_id: 10, name: 'puerto obaldía'},
  {province_id: 10, name: 'tubuala'},
  {province_id: 11, name: 'cémaco'},
  {province_id: 11, name: 'sambú'},
  {province_id: 12, name: 'kankintú'},
  {province_id: 12, name: 'kusapín'},
  {province_id: 12, name: 'besikó'},
  {province_id: 12, name: 'mironó'},
  {province_id: 12, name: 'nole düima'},
  {province_id: 12, name: 'müna'},
  {province_id: 12, name: 'ñürüm'},
  {province_id: 12, name: 'jirondai'},
  {province_id: 12, name: 'santa catalina'}])
