EducativeArea.create([
  { name: 'abogacía / derecho / leyes' },
  { name: 'actuaría' },
  { name: 'acuicultura' },
  { name: 'adm. de empresas' },
  { name: 'adm. y gestión pública' },
  { name: 'administración agropecuaria' },
  { name: 'agrimensor' },
  { name: 'agronegocios' },
  { name: 'antropología' },
  { name: 'análisis de sistemas' },
  { name: 'apoderado aduanal' },
  { name: 'arqueología' },
  { name: 'arquitectura' },
  { name: 'asesoría legal internacional' },
  { name: 'asesoría en comercio exterior' },
  { name: 'asesoría en comercio exterior jubilado' },
  { name: 'asistente de tráfico' },
  { name: 'astronomía' },
  { name: 'bachiller' },
  { name: 'bellas artes' },
  { name: 'bibliotecología' },
  { name: 'biofisica' },
  { name: 'bioingeniería' },
  { name: 'biología' },
  { name: 'bioquímica' },
  { name: 'biotecnología' },
  { name: 'call center' },
  { name: 'capacitación comercio exterior' },
  { name: 'cartografía' },
  { name: 'ciencias físicas' },
  { name: 'ciencias políticas' },
  { name: 'ciencias de la educación' },
  { name: 'ciencias del ejercicio / educacion física' },
  { name: 'comercio int./ext.' },
  { name: 'compras internacionales/importación' },
  { name: 'computación / informática' },
  { name: 'comunicación audiovisual' },
  { name: 'comunicación social' },
  { name: 'construcción / obras civiles' },
  { name: 'consultorías comercio exterior' },
  { name: 'contabilidad / auditoría' },
  { name: 'dibujo técnico' },
  { name: 'diseño gráfico' },
  { name: 'diseño industrial' },
  { name: 'diseño de imagen y sonido' },
  { name: 'diseño de vestuario / textil / modas' },
  { name: 'ecología' },
  { name: 'economía' },
  { name: 'educacion' },
  { name: 'electricidad' },
  { name: 'electrónica' },
  { name: 'enfermería' },
  { name: 'escribanía' },
  { name: 'estadística' },
  { name: 'farmacia' },
  { name: 'filosofía' },
  { name: 'finanzas' },
  { name: 'finanzas internacionales' },
  { name: 'fisioterapia' },
  { name: 'fonoaudiologia' },
  { name: 'fotografía' },
  { name: 'gastronomía / cocina' },
  { name: 'geofísica' },
  { name: 'geografía' },
  { name: 'geología / geomensura / topografía' },
  { name: 'hidráulica' },
  { name: 'historia' },
  { name: 'hotelería' },
  { name: 'ing. - otros' },
  { name: 'ing. aerospacial' },
  { name: 'ing. agropecuario' },
  { name: 'ing. agrónomo' },
  { name: 'ing. alimentos' },
  { name: 'ing. ambiental' },
  { name: 'ing. comercial' },
  { name: 'ing. electrónica' },
  { name: 'ing. eléctrica' },
  { name: 'ing. forestal' },
  { name: 'ing. hidraúlica' },
  { name: 'ing. industrial' },
  { name: 'ing. informática' },
  { name: 'ing. matemática' },
  { name: 'ing. mecánica/metalúrgica' },
  { name: 'ing. naval' },
  { name: 'ing. nuclear' },
  { name: 'ing. obras civiles/construcción' },
  { name: 'ing. pesquera / cultivos marinos' },
  { name: 'ing. petróleo' },
  { name: 'ing. química' },
  { name: 'ing. recursos hídricos' },
  { name: 'ing. sonido' },
  { name: 'ing. telecomunicaciones' },
  { name: 'ing. transporte' },
  { name: 'ing. en materiales' },
  { name: 'ing. en minas' },
  { name: 'ing. en sistemas' },
  { name: 'ingeniero en construcción' },
  { name: 'ingeniero vial' },
  { name: 'intérprete' },
  { name: 'kinesiología' },
  { name: 'laboratorio (mecánica) dental' },
  { name: 'literatura' },
  { name: 'maestro mayor de obras' },
  { name: 'marketing / comercialización' },
  { name: 'matemáticas' },
  { name: 'mecánica / metalúrgica' },
  { name: 'medicina' },
  { name: 'medio ambiente' },
  { name: 'mercadotecnia internacional' },
  { name: 'minería / petróleo / gas' },
  { name: 'música' },
  { name: 'nutrición' },
  { name: 'oceanografía' },
  { name: 'odontología' },
  { name: 'organización industrial' },
  { name: 'otra' },
  { name: 'paisajismo' },
  { name: 'periodismo' },
  { name: 'perito mercantil' },
  { name: 'procesos / calidad total' },
  { name: 'programación' },
  { name: 'psicología' },
  { name: 'psicopedagogía' },
  { name: 'publicidad' },
  { name: 'química' },
  { name: 'recursos humanos' },
  { name: 'relaciones internacionales' },
  { name: 'relaciones públicas' },
  { name: 'secretariado' },
  { name: 'seguridad industrial' },
  { name: 'seguros' },
  { name: 'sociología' },
  { name: 'tecnico' },
  { name: 'tecnología médica / laboratorio' },
  { name: 'tecnología de alimentos' },
  { name: 'tecnologías de la información' },
  { name: 'telecomunicaciones' },
  { name: 'terapia ocupacional' },
  { name: 'trabajo social' },
  { name: 'traducción ' },
  { name: 'transporte' },
  { name: 'turismo' },
  { name: 'ventas internacionales/exportación' },
  { name: 'veterinaria' }
  ])
