#encoding: UTF-8

Township.create([
  { district_id: 1, name: 'bocas del toro'},
  { district_id: 1, name: 'bastimentos'},
  { district_id: 1, name: 'cauchero'},
  { district_id: 1, name: 'punta laurel'},
  { district_id: 1, name: 'tierra oscura'},
  { district_id: 2, name: 'changuinola'},
  { district_id: 2, name: 'almirante'},
  { district_id: 2, name: 'guabito'},
  { district_id: 2, name: 'teribe'},
  { district_id: 2, name: 'valle del risco'},
  { district_id: 2, name: 'valle del risco'},
  { district_id: 3, name: 'chiriquí grande'},
  { district_id: 3, name: 'miramar'},
  { district_id: 3, name: 'punta peña'},
  { district_id: 3, name: 'punta róbalo'},
  { district_id: 3, name: 'rambala'},
  { district_id: 4, name: 'aguadulce'},
  { district_id: 4, name: 'el cristo'},
  { district_id: 4, name: 'el roble'},
  { district_id: 4, name: 'pocrí'},
  { district_id: 4, name: 'barrios unidos'},
  { district_id: 5, name: 'antón'},
  { district_id: 5, name: 'cabuya'},
  { district_id: 5, name: 'el chirú'},
  { district_id: 5, name: 'el retiro'},
  { district_id: 5, name: 'el valle'},
  { district_id: 5, name: 'juan díaz'},
  { district_id: 5, name: 'río hato'},
  { district_id: 5, name: 'san juan de dios'},
  { district_id: 5, name: 'santa rita'},
  { district_id: 5, name: 'caballero'},
  { district_id: 6, name: 'la pintada'},
  { district_id: 7, name: 'natá'},
  { district_id: 8, name: 'ola'},
  { district_id: 9, name: 'penonome'},
  { district_id: 9, name: 'canaveral'},
  { district_id: 10, name: 'barrio norte'},
  { district_id: 10, name: 'barrio sur'},
  { district_id: 10, name: 'buena vista'},
  { district_id: 10, name: 'cativa'},
  { district_id: 10, name: 'ciricito'},
  { district_id: 10, name: 'cristóbal'},
  { district_id: 10, name: 'escobal'},
  { district_id: 10, name: 'limon'},
  { district_id: 10, name: 'nueva providencia'},
  { district_id: 10, name: 'puerto pilon'},
  { district_id: 10, name: 'sabanitas'},
  { district_id: 10, name: 'salamanca'},
  { district_id: 10, name: 'san juan'},
  { district_id: 10, name: 'santa rosa'},
  { district_id: 11, name: 'nuevo chagres'},
  { district_id: 11, name: 'achiote'},
  { district_id: 11, name: 'el guabo'},
  { district_id: 11, name: 'la encantada'},
  { district_id: 11, name: 'palmas bellas'},
  { district_id: 11, name: 'pina'},
  { district_id: 11, name: 'salud'},
  { district_id: 12, name: 'donoso'},
  { district_id: 13, name: 'portobelo'},
  { district_id: 14, name: 'santa isabel'},
  { district_id: 15, name: 'alanje'},
  { district_id: 15, name: 'divalá'},
  { district_id: 15, name: 'el tejar'},
  { district_id: 15, name: 'guarumal'},
  { district_id: 15, name: 'palo grande'},
  { district_id: 15, name: 'querévalo'},
  { district_id: 15, name: 'santo tomás'},
  { district_id: 15, name: 'canta gallo'},
  { district_id: 15, name: 'nuevo méxico'},
  { district_id: 16, name: 'puerto armuelles'},
  { district_id: 16, name: 'limones'},
  { district_id: 16, name: 'progreso'},
  { district_id: 16, name: 'baco'},
  { district_id: 16, name: 'rodolfo aguilar delgado'},
  { district_id: 17, name: 'boquerón'},
  { district_id: 17, name: 'bagala'},
  { district_id: 17, name: 'cordillera'},
  { district_id: 17, name: 'guabal'},
  { district_id: 17, name: 'guayabal'},
  { district_id: 17, name: 'paraíso'},
  { district_id: 17, name: 'pedregal'},
  { district_id: 17, name: 'tijeras'},
  { district_id: 18, name: 'bajo boquete'},
  { district_id: 18, name: 'caldera'},
  { district_id: 18, name: 'palmira'},
  { district_id: 18, name: 'alto boquete'},
  { district_id: 18, name: 'jaramillo'},
  { district_id: 18, name: 'los naranjos'},
  { district_id: 19, name: 'la concepción'},
  { district_id: 19, name: 'aserrío de gariché'},
  { district_id: 19, name: 'bugaba'},
  { district_id: 19, name: 'cerro punta'},
  { district_id: 19, name: 'gómez'},
  { district_id: 19, name: 'la estrella'},
  { district_id: 19, name: 'san andrés'},
  { district_id: 19, name: 'santa marta'},
  { district_id: 19, name: 'santa rosa'},
  { district_id: 19, name: 'santo domingo'},
  { district_id: 19, name: 'sortová'},
  { district_id: 19, name: 'volcán'},
  { district_id: 19, name: 'el bongo'},
  { district_id: 20, name: 'david'},
  { district_id: 20, name: 'chiriquí'},
  { district_id: 20, name: 'las lomas'},
  { district_id: 20, name: 'bijagual'},
  { district_id: 20, name: 'las lomas'},
  { district_id: 20, name: 'las cochea'},
  { district_id: 20, name: 'guacá'},
  { district_id: 20, name: 'pedregal'},
  { district_id: 20, name: 'san carlos'},
  { district_id: 20, name: 'san pablo nuevo'},
  { district_id: 20, name: 'san pablo viejo'},
  { district_id: 21, name: 'dolega'},
  { district_id: 21, name: 'dos ríos'},
  { district_id: 21, name: 'los anastacios'},
  { district_id: 21, name: 'potrerillos'},
  { district_id: 21, name: 'potrerillos abajo'},
  { district_id: 21, name: 'rovira'},
  { district_id: 21, name: 'tinajas'},
  { district_id: 21, name: 'los algarrobos'},
  { district_id: 22, name: 'gualaca'},
  { district_id: 22, name: 'hornito'},
  { district_id: 22, name: 'los ángeles'},
  { district_id: 22, name: 'paja de sombrero'},
  { district_id: 22, name: 'rincón'},
  { district_id: 23, name: 'remedios'},
  { district_id: 23, name: 'el nancito'},
  { district_id: 23, name: 'el porvenir'},
  { district_id: 23, name: 'el puerto'},
  { district_id: 23, name: 'santa lucía'},
  { district_id: 24, name: 'río sereno'},
  { district_id: 24, name: 'breñón'},
  { district_id: 24, name: 'cañas gordas'},
  { district_id: 24, name: 'monte lirio'},
  { district_id: 24, name: 'plaza de caisán'},
  { district_id: 24, name: 'santa cruz'},
  { district_id: 24, name: 'dominical'},
  { district_id: 24, name: 'santa clara'},
  { district_id: 25, name: 'las lajas'},
  { district_id: 25, name: 'juay'},
  { district_id: 25, name: 'san félix'},
  { district_id: 25, name: 'lajas adentro'},
  { district_id: 25, name: 'santa cruz'},
  { district_id: 26, name: 'horconcitos'},
  { district_id: 26, name: 'boca chica'},
  { district_id: 26, name: 'boca del monte'},
  { district_id: 26, name: 'san juan'},
  { district_id: 26, name: 'san lorenzo'},
  { district_id: 27, name: 'tolé'},
  { district_id: 27, name: 'cerro viejo'},
  { district_id: 27, name: 'lajas de tolé'},
  { district_id: 27, name: 'potrero de caña'},
  { district_id: 27, name: 'quebrada de piedra'},
  { district_id: 27, name: 'bella vista'},
  { district_id: 27, name: 'el cristo'},
  { district_id: 27, name: 'justo fidel palacios'},
  { district_id: 27, name: 'veladero'},
  { district_id: 28, name: 'la palma'},
  { district_id: 28, name: 'camoganti'},
  { district_id: 28, name: 'chepigana'},
  { district_id: 28, name: 'garachiné'},
  { district_id: 28, name: 'jaque'},
  { district_id: 28, name: 'puerto piña'},
  { district_id: 28, name: 'río congo'},
  { district_id: 28, name: 'río iglesias'},
  { district_id: 28, name: 'sambú'},
  { district_id: 28, name: 'setegantí'},
  { district_id: 28, name: 'taimatí'},
  { district_id: 28, name: 'tucuti'},
  { district_id: 28, name: 'agua fria'},
  { district_id: 28, name: 'cucunati'},
  { district_id: 28, name: 'río congo arriba'},
  { district_id: 28, name: 'santa fe'},
  { district_id: 29, name: 'el real de santa maria'},
  { district_id: 29, name: 'boca de cupe'},
  { district_id: 29, name: 'paya'},
  { district_id: 29, name: 'pinogana'},
  { district_id: 29, name: 'pucuro'},
  { district_id: 29, name: 'yape'},
  { district_id: 29, name: 'yaviza'},
  { district_id: 29, name: 'meteti'},
  { district_id: 29, name: 'comarca kuna de wargandi'},
  { district_id: 30, name: 'chitré'},
  { district_id: 30, name: 'la arena'},
  { district_id: 30, name: 'monagrillo'},
  { district_id: 30, name: 'llano bonito'},
  { district_id: 30, name: 'san juan bautista'},
  { district_id: 31, name: 'las minas'},
  { district_id: 31, name: 'chepo'},
  { district_id: 31, name: 'chumical'},
  { district_id: 31, name: 'el toro'},
  { district_id: 31, name: 'leones'},
  { district_id: 31, name: 'quebrada del rosarío'},
  { district_id: 31, name: 'quebrada el ciprián'},
  { district_id: 32, name: 'los pozos'},
  { district_id: 32, name: 'el capurí'},
  { district_id: 32, name: 'el calabacito'},
  { district_id: 32, name: 'el cedro'},
  { district_id: 32, name: 'la pitaloza'},
  { district_id: 32, name: 'los cerritos'},
  { district_id: 32, name: 'los cerros de paja'},
  { district_id: 32, name: 'las llanas'},
  { district_id: 33, name: 'ocú'},
  { district_id: 33, name: 'cerro largo'},
  { district_id: 33, name: 'los llanos'},
  { district_id: 33, name: 'llano grande'},
  { district_id: 33, name: 'peñas chatas'},
  { district_id: 33, name: 'el tijera'},
  { district_id: 33, name: 'menchaca'},
  { district_id: 33, name: 'entradero del castillo'},
  { district_id: 34, name: 'parita'},
  { district_id: 34, name: 'los castillos'},
  { district_id: 34, name: 'llano de la cruz'},
  { district_id: 34, name: 'paris'},
  { district_id: 34, name: 'portobelillo'},
  { district_id: 34, name: 'potuga'},
  { district_id: 35, name: 'pesé'},
  { district_id: 35, name: 'las cabras'},
  { district_id: 35, name: 'el pajaro'},
  { district_id: 35, name: 'el barrero'},
  { district_id: 35, name: 'el pedregoso'},
  { district_id: 35, name: 'el ciruelo'},
  { district_id: 35, name: 'sabana grande'},
  { district_id: 35, name: 'rincón hondo'},
  { district_id: 36, name: 'santa maria'},
  { district_id: 36, name: 'chupampa'},
  { district_id: 36, name: 'el rincón'},
  { district_id: 36, name: 'el limón'},
  { district_id: 36, name: 'los canelos'},
  { district_id: 37, name: 'guararé'},
  { district_id: 37, name: 'el espinal'},
  { district_id: 37, name: 'el macano'},
  { district_id: 37, name: 'guararé arriba'},
  { district_id: 37, name: 'la enea'},
  { district_id: 37, name: 'la pasera'},
  { district_id: 37, name: 'las trancas'},
  { district_id: 37, name: 'llano abajo'},
  { district_id: 37, name: 'el hato'},
  { district_id: 37, name: 'perales'},
  { district_id: 43, name: 'altos de güera'},
  { district_id: 43, name: 'cañas'},
  { district_id: 43, name: 'el bebedero'},
  { district_id: 43, name: 'el cacao'},
  { district_id: 43, name: 'el cortezo'},
  { district_id: 43, name: 'flores'},
  { district_id: 43, name: 'guánico'},
  { district_id: 43, name: 'la tronosa'},
  { district_id: 43, name: 'cambutal'},
  { district_id: 43, name: 'isla de cañas'},
  { district_id: 38, name: 'las tablas'},
  { district_id: 38, name: 'bajo corral'},
  { district_id: 38, name: 'bayano'},
  { district_id: 38, name: 'el carate'},
  { district_id: 38, name: 'el cocal'},
  { district_id: 38, name: 'el manantial'},
  { district_id: 38, name: 'el munoz'},
  { district_id: 38, name: 'la laja'},
  { district_id: 38, name: 'la miel'},
  { district_id: 38, name: 'san miguel'},
  { district_id: 38, name: 'santo domingo'},
  { district_id: 38, name: 'la palma'},
  { district_id: 38, name: 'la tiza'},
  { district_id: 38, name: 'el sesteadero'},
  { district_id: 38, name: 'sesteadero'},
  { district_id: 38, name: 'las palmitas'},
  { district_id: 38, name: 'valle rico'},
  { district_id: 38, name: 'las tablas abajo'},
  { district_id: 38, name: 'vallerriquito'},
  { district_id: 38, name: 'nuario'},
  { district_id: 38, name: 'pena blanca'},
  { district_id: 38, name: 'río hondo'},
  { district_id: 38, name: 'san jose'},
  { district_id: 39, name: 'la villa de los santos'},
  { district_id: 39, name: 'el guásimo'},
  { district_id: 39, name: 'la colorada'},
  { district_id: 39, name: 'la espigadilla'},
  { district_id: 39, name: 'las cruces'},
  { district_id: 39, name: 'las guabas'},
  { district_id: 39, name: 'los angeles'},
  { district_id: 39, name: 'los olivos'},
  { district_id: 39, name: 'llano largo'},
  { district_id: 39, name: 'sabana grande'},
  { district_id: 39, name: 'santa ana'},
  { district_id: 39, name: 'tres quebradas'},
  { district_id: 39, name: 'villa lourdes'},
  { district_id: 39, name: 'agua buena'},
  { district_id: 40, name: 'macaracas'},
  { district_id: 40, name: 'bahía honda'},
  { district_id: 40, name: 'bajos de güera'},
  { district_id: 40, name: 'corozal'},
  { district_id: 40, name: 'chupá'},
  { district_id: 40, name: 'espino amarillo'},
  { district_id: 40, name: 'la mesa'},
  { district_id: 40, name: 'llano de piedras'},
  { district_id: 40, name: 'las palmas'},
  { district_id: 40, name: 'mogollón'},
  { district_id: 41, name: 'pedasí'},
  { district_id: 41, name: 'los asientos'},
  { district_id: 41, name: 'mariabé'},
  { district_id: 41, name: 'purío'},
  { district_id: 41, name: 'oria arriba'},
  { district_id: 42, name: 'pocrí'},
  { district_id: 42, name: 'el cañafístulo'},
  { district_id: 42, name: 'lajamina'},
  { district_id: 42, name: 'paritilla'},
  { district_id: 43, name: 'tonosí'},
  { district_id: 51, name: 'arraiján'},
  { district_id: 51, name: 'juan demostenes arosemena'},
  { district_id: 51, name: 'nuevo emperador'},
  { district_id: 51, name: 'santa clara'},
  { district_id: 51, name: 'veracruz'},
  { district_id: 51, name: 'vista alegre'},
  { district_id: 44, name: 'san miguel'},
  { district_id: 44, name: 'la ensenada'},
  { district_id: 44, name: 'la esmeralda'},
  { district_id: 44, name: 'la guinea'},
  { district_id: 44, name: 'pedro gonzalez'},
  { district_id: 44, name: 'saboga'},
  { district_id: 53, name: 'capira'},
  { district_id: 53, name: 'caimito'},
  { district_id: 53, name: 'campana'},
  { district_id: 53, name: 'cermeno'},
  { district_id: 53, name: 'ciri de los sotos'},
  { district_id: 53, name: 'ciri grande'},
  { district_id: 53, name: 'la trinidad'},
  { district_id: 53, name: 'las ollas arriba'},
  { district_id: 53, name: 'lidice'},
  { district_id: 53, name: 'villa carmen'},
  { district_id: 53, name: 'villa rosarío'},
  { district_id: 54, name: 'chame'},
  { district_id: 54, name: 'bejuco'},
  { district_id: 54, name: 'buenos aires'},
  { district_id: 54, name: 'chica'},
  { district_id: 54, name: 'el libano'},
  { district_id: 54, name: 'las lajas'},
  { district_id: 54, name: 'nueva gorgona'},
  { district_id: 54, name: 'punta chame'},
  { district_id: 54, name: 'sajalices'},
  { district_id: 54, name: 'sora'},
  { district_id: 45, name: 'chepo'},
  { district_id: 45, name: 'cañita'},
  { district_id: 45, name: 'chepillo'},
  { district_id: 45, name: 'el llano'},
  { district_id: 45, name: 'las margaritas'},
  { district_id: 45, name: 'santa cruz de chinina'},
  { district_id: 45, name: 'comarca kuna de madungandi'},
  { district_id: 45, name: 'tortí'},
  { district_id: 46, name: 'chimán'},
  { district_id: 46, name: 'brujas'},
  { district_id: 46, name: 'gonzalo vasquez'},
  { district_id: 46, name: 'pasiga'},
  { district_id: 46, name: 'unión santeña'},
  { district_id: 50, name: 'barrio balboa'},
  { district_id: 50, name: 'barrio colón'},
  { district_id: 50, name: 'amador'},
  { district_id: 50, name: 'arosemena'},
  { district_id: 50, name: 'el arado'},
  { district_id: 50, name: 'el coco'},
  { district_id: 50, name: 'feuillet'},
  { district_id: 50, name: 'guadalupe'},
  { district_id: 50, name: 'herrera'},
  { district_id: 50, name: 'hurtado'},
  { district_id: 50, name: 'iturralde'},
  { district_id: 50, name: 'la represa'},
  { district_id: 50, name: 'los díaz'},
  { district_id: 50, name: 'mendoza'},
  { district_id: 50, name: 'obaldía'},
  { district_id: 50, name: 'playa leona'},
  { district_id: 50, name: 'puerto caimito'},
  { district_id: 47, name: '24 de diciembre'},
  { district_id: 47, name: 'alcalde díaz'},
  { district_id: 47, name: 'ancón'},
  { district_id: 47, name: 'betania'},
  { district_id: 47, name: 'bella vista'},
  { district_id: 47, name: 'caimitillo'},
  { district_id: 47, name: 'chilibre'},
  { district_id: 47, name: 'el chorrillo'},
  { district_id: 47, name: 'calidonia'},
  { district_id: 47, name: 'curundu'},
  { district_id: 47, name: 'ernesto cordoba campos'},
  { district_id: 47, name: 'juan díaz'},
  { district_id: 47, name: 'las cumbres'},
  { district_id: 47, name: 'las mañanitas'},
  { district_id: 47, name: 'pacora'},
  { district_id: 47, name: 'parque lefevre'},
  { district_id: 47, name: 'pedregal'},
  { district_id: 47, name: 'pueblo nuevo'},
  { district_id: 47, name: 'río abajo'},
  { district_id: 47, name: 'san felipe'},
  { district_id: 47, name: 'san francisco'},
  { district_id: 47, name: 'san martín'},
  { district_id: 47, name: 'tocumen'},
  { district_id: 52, name: 'san carlos'},
  { district_id: 52, name: 'el espino'},
  { district_id: 52, name: 'el higo'},
  { district_id: 52, name: 'guayabito'},
  { district_id: 52, name: 'la ermita'},
  { district_id: 52, name: 'la laguna'},
  { district_id: 52, name: 'las uvas'},
  { district_id: 52, name: 'los llanitos'},
  { district_id: 48, name: 'amelia denis de icaza'},
  { district_id: 48, name: 'belisarío porras'},
  { district_id: 48, name: 'jose domingo espinar'},
  { district_id: 48, name: 'mateo iturralde'},
  { district_id: 48, name: 'victoriano lorenzo'},
  { district_id: 48, name: 'arnulfo arias'},
  { district_id: 48, name: 'belisarío frías'},
  { district_id: 48, name: 'omar torrijos'},
  { district_id: 48, name: 'rufina alfaro'},
  { district_id: 49, name: 'taboga'},
  { district_id: 49, name: 'otoque occidente'},
  { district_id: 49, name: 'otoque oriente'},
  { district_id: 55, name: 'atalaya'},
  { district_id: 55, name: 'el barrito'},
  { district_id: 55, name: 'la montañuela'},
  { district_id: 55, name: 'la carrillo'},
  { district_id: 55, name: 'san antonio'},
  { district_id: 57, name: 'cañazas'},
  { district_id: 57, name: 'cerro de plata'},
  { district_id: 57, name: 'los valles'},
  { district_id: 57, name: 'san marcelo'},
  { district_id: 57, name: 'el picador'},
  { district_id: 57, name: 'san jose'},
  { district_id: 57, name: 'el aromillo'},
  { district_id: 57, name: 'las cruces'},
  { district_id: 57, name: 'alto ibala'},
  { district_id: 57, name: 'bocle'},
  { district_id: 58, name: 'la mesa'},
  { district_id: 58, name: 'bisballes'},
  { district_id: 58, name: 'boro'},
  { district_id: 58, name: 'san bartolo'},
  { district_id: 58, name: 'llano grande'},
  { district_id: 58, name: 'los milagros'},
  { district_id: 58, name: 'el higo'},
  { district_id: 61, name: 'montijo'},
  { district_id: 61, name: 'gobernadora'},
  { district_id: 61, name: 'la garceana'},
  { district_id: 61, name: 'leones'},
  { district_id: 61, name: 'pilon'},
  { district_id: 61, name: 'cebaco'},
  { district_id: 61, name: 'costa hermosa'},
  { district_id: 61, name: 'union del norte'},
  { district_id: 65, name: 'santiago'},
  { district_id: 65, name: 'la colorada'},
  { district_id: 65, name: 'la peña'},
  { district_id: 65, name: 'la raya de santa maría'},
  { district_id: 65, name: 'ponuga'},
  { district_id: 65, name: 'san pedro del espino'},
  { district_id: 65, name: 'canto del llano'},
  { district_id: 65, name: 'los algarrobos'},
  { district_id: 65, name: 'san martin de porres'},
  { district_id: 65, name: 'urraca'},
  { district_id: 65, name: 'edwin fabrega'},
  { district_id: 65, name: 'carlos santana avila'},
  { district_id: 65, name: 'la soledad'},
  { district_id: 65, name: 'rincon largo'},
  { district_id: 65, name: 'el llanito'},
  { district_id: 65, name: 'rodrigo luque'},
  { district_id: 66, name: 'sona'},
  { district_id: 66, name: 'bahia honda'},
  { district_id: 66, name: 'calidonia'},
  { district_id: 66, name: 'cative'},
  { district_id: 66, name: 'el marañon'},
  { district_id: 66, name: 'guarumal'},
  { district_id: 66, name: 'la soledad'},
  { district_id: 66, name: 'quebrada de oro'},
  { district_id: 66, name: 'río grande'},
  { district_id: 66, name: 'rodeo viejo'},
  { district_id: 66, name: 'hicaco'},
  { district_id: 56, name: 'calobre'},
  { district_id: 56, name: 'barnizal'},
  { district_id: 56, name: 'chitra'},
  { district_id: 56, name: 'el cocla'},
  { district_id: 56, name: 'el potrero'},
  { district_id: 56, name: 'la laguna'},
  { district_id: 56, name: 'la raya'},
  { district_id: 56, name: 'la tetilla'},
  { district_id: 56, name: 'la yeguada'},
  { district_id: 56, name: 'las guias'},
  { district_id: 56, name: 'mojaras'},
  { district_id: 56, name: 'san jose'},
  { district_id: 59, name: 'las palmas'},
  { district_id: 59, name: 'cerro de casa'},
  { district_id: 59, name: 'corozal'},
  { district_id: 59, name: 'el maría'},
  { district_id: 59, name: 'el prado'},
  { district_id: 59, name: 'lola'},
  { district_id: 59, name: 'pixvae'},
  { district_id: 59, name: 'puerto vidal'},
  { district_id: 59, name: 'zapotillo'},
  { district_id: 59, name: 'san martin de porres'},
  { district_id: 59, name: 'vigui'},
  { district_id: 59, name: 'manuel encarnacion amador terreros'},
  { district_id: 60, name: 'mariato'},
  { district_id: 60, name: 'arenas'},
  { district_id: 60, name: 'el cacao'},
  { district_id: 60, name: 'quebro'},
  { district_id: 60, name: 'tebarío'},
  { district_id: 62, name: 'río de jesus'},
  { district_id: 62, name: 'las huacas'},
  { district_id: 62, name: 'los castillos'},
  { district_id: 62, name: 'utira'},
  { district_id: 62, name: '14 de noviembre'},
  { district_id: 62, name: 'nuevo san juan'},
  { district_id: 63, name: 'san francisco'},
  { district_id: 63, name: 'corral falso'},
  { district_id: 63, name: 'los hatillos'},
  { district_id: 63, name: 'remance'},
  { district_id: 63, name: 'san juan'},
  { district_id: 63, name: 'san josé'},
  { district_id: 64, name: 'santa fe'},
  { district_id: 64, name: 'calovebora'},
  { district_id: 64, name: 'el alto'},
  { district_id: 64, name: 'el cuay'},
  { district_id: 64, name: 'el pantano'},
  { district_id: 64, name: 'gatuncito'},
  { district_id: 64, name: 'río luis'},
  { district_id: 64, name: 'ruben cantú'},
  { district_id: 68, name: 'narganá'},
  { district_id: 67, name: 'ailigandí'},
  { district_id: 69, name: 'puerto obaldía'},
  { district_id: 70, name: 'tubuala'},
  { district_id: 71, name: 'cirilo guainora'},
  { district_id: 71, name: 'lajas blancas'},
  { district_id: 71, name: 'manuel ortega'},
  { district_id: 72, name: 'río sabalo'},
  { district_id: 72, name: 'jingurudo'},
  { district_id: 75, name: 'soloy'},
  { district_id: 75, name: 'boca de balsa'},
  { district_id: 75, name: 'camarón arriba'},
  { district_id: 75, name: 'cerro banco'},
  { district_id: 75, name: 'cerro de patena'},
  { district_id: 75, name: 'emplanada de chorcha'},
  { district_id: 75, name: 'namnoni'},
  { district_id: 75, name: 'niba'},
  { district_id: 76, name: 'hato pilon'},
  { district_id: 76, name: 'cascabel'},
  { district_id: 76, name: 'hato corotú'},
  { district_id: 76, name: 'hato culantro'},
  { district_id: 76, name: 'hato jobo'},
  { district_id: 76, name: 'hato juli'},
  { district_id: 76, name: 'quebrada de loro'},
  { district_id: 76, name: 'salto dupi'},
  { district_id: 78, name: 'chichica'},
  { district_id: 78, name: 'alto caballero'},
  { district_id: 78, name: 'bakama'},
  { district_id: 78, name: 'cerro cana'},
  { district_id: 78, name: 'cerro puerco'},
  { district_id: 78, name: 'krua'},
  { district_id: 78, name: 'maraca'},
  { district_id: 77, name: 'nole düima'},
  { district_id: 73, name: 'kankintú'},
  { district_id: 74, name: 'kusapín'},
  { district_id: 79, name: 'ñurün'},
  { district_id: 80, name: 'jirondai'},
  { district_id: 81, name: 'santa catalina'}])
